"""inclusão de campo resondido na tabvela contato

Revision ID: 569a675b891a
Revises: 85e62bcf0e05
Create Date: 2025-12-04 10:23:27.965714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569a675b891a'
down_revision = '85e62bcf0e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
